### ISSUE TITLE
Insecure jquery versie

### ISSUE THREAD

**Issue by MagicLegend** [SanguPackage/Script#14]
In een profielpagina van een speler wordt een request gemaakt naar `http://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js`, welke een https resource zou moeten zijn.

**Comment by Laoujin** [comment]
Zou dat niet iets van TribalWars zelf zijn want ik vind nergens "ajax.googleapis.com" terug in de code van het package...

**Comment by MagicLegend** [comment]
Nope, want als ik sangu uitzet is de error weg (vandaar dat ik 'm hier neer had gezet). Had nog niet verder gezocht in de code; was druk met andere dingen :p

**Comment by Laoujin** [comment]
Het zit em in twstats.com dat https en http aan het mixen is.
Ze zullen ooit wel eens een fix doen zeker :p

Vb link met zelfde probleem:
https://nl.twstats.com/nl55/index.php?page=player&mode=conquers&id=2243692&pn=1&type=1&enemy=-1&enemyt=-1&min=&max=
